services:
  frontend:
    build: ./frontend
    container_name: fe-demo
    ports:
      - "8081:80"
    depends_on:
      - gateway

  gateway:
    build: ./services/gateway
    container_name: api-gateway
    environment:
      USER_SERVICE_URL: http://user-service:3001
      INVENTORY_SERVICE_URL: http://inventory-service:3002
      ORDER_SERVICE_URL: http://order-service:3003
      ORCHESTRATOR_SERVICE_URL: http://orchestrator-service:3007
      NOTIFICATION_SERVICE_URL: http://notification-service:3006
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - inventory-service
      - order-service
      - orchestrator-service

  user-service:
    build: ./services/user-service
    container_name: user-service
    environment:
      DB_HOST: db-user
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: userdb
    depends_on:
      - db-user

  inventory-service:
    build: ./services/inventory-service
    container_name: inventory-service
    environment:
      DB_HOST: db-inventory
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: inventorydb
      REDIS_URL: redis://redis:6379
      ORDER_SERVICE_URL: http://order-service:3003
    depends_on:
      - db-inventory
      - redis

  order-service:
    build: ./services/order-service
    container_name: order-service
    environment:
      DB_HOST: db-order
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: orderdb
      REDIS_URL: redis://redis:6379
    depends_on:
      - db-order
      - redis

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    environment:
      REDIS_URL: redis://redis:6379
      ORDER_SERVICE_URL: http://order-service:3003
    depends_on:
      - redis
      - order-service

  delivery-service:
    build: ./services/delivery-service
    container_name: delivery-service
    environment:
      REDIS_URL: redis://redis:6379
      ORDER_SERVICE_URL: http://order-service:3003
    depends_on:
      - redis
      - order-service

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  orchestrator-service:
    build: ./services/orchestrator-service
    container_name: orchestrator-service
    environment:
      ORDER_SERVICE_URL: http://order-service:3003
      INVENTORY_SERVICE_URL: http://inventory-service:3002
      PAYMENT_SERVICE_URL: http://payment-service:3004
      DELIVERY_SERVICE_URL: http://delivery-service:3005
    depends_on:
      - order-service
      - inventory-service
      - payment-service
      - delivery-service

  redis:
    image: redis:7-alpine
    container_name: redis-bus
    ports:
      - "6379:6379"

  db-user:
    image: postgres:16-alpine
    container_name: db-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"

  db-order:
    image: postgres:16-alpine
    container_name: db-order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5435:5432"

  db-inventory:
    image: postgres:16-alpine
    container_name: db-inventory
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventorydb
    ports:
      - "5436:5432"
